# Database Configuration for E-commerce Analytics Pipeline
database:
  host: localhost
  port: 5432
  database: ecommerce_analytics
  user: analytics_user
  password: analytics_password
  
  # Connection pool settings
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600
  
  # SSL settings (for production)
  ssl_mode: disable
  
  # Performance settings
  statement_timeout: 30000  # 30 seconds
  idle_in_transaction_session_timeout: 300000  # 5 minutes 